"""
Axis 1 – AI/manipulation classifier  (text + image)
Axis 2 – Context confidence  (caption–image mismatch, misleading language)
"""
from __future__ import annotations

import base64
import io
import re
from typing import Optional

import torch


# ─────────────────────────────────────────────────────────────────────────────
# Shared patterns
# ─────────────────────────────────────────────────────────────────────────────

_NEWS_SIGNALS = re.compile(
    r"\b(breaking|exclusive|report|president|minister|attack|killed|war|"
    r"crisis|government|official|election|court|police|military|announced|"
    r"confirmed|according to|sources say|just in|developing)\b",
    re.IGNORECASE,
)

_EXPLICIT_AI_SIGNALS = re.compile(
    r"\b(AI-generated|deepfake|synthetic|generated by|made with AI|"
    r"DALL-E|Midjourney|Stable Diffusion|ChatGPT|GPT-4|GPT-3|Sora|"
    r"created with AI|produced by AI)\b",
    re.IGNORECASE,
)

# Phrases that are statistically over-represented in LLM-generated text
_AI_PROSE_PATTERNS = re.compile(
    r"\b(delve|delves|delving|tailor(?:ed|ing)?|underscore[sd]?|empower(?:ing|s)?|"
    r"leverage[sd]?|synergy|paradigm|holistic(?:ally)?|cutting-edge|"
    r"state-of-the-art|innovative(?:ly)?|transformative|seamlessly|"
    r"robust(?:ly)?|comprehensive(?:ly)?|multifaceted|nuanced|"
    r"streamline[sd]?|harness(?:ing|es)?|foster(?:ing|s)?|"
    r"unlock(?:ing|s)?|scalable|proactive(?:ly)?|dynamic(?:ally)?|"
    r"navigate[sd]?|unleash(?:es|ing)?|impactful|actionable)\b|"
    r"it\s+is\s+(?:important|crucial|essential|worth)\s+to\s+(?:note|mention|highlight)|"
    r"it\'s\s+(?:important|crucial|essential|worth)\s+(?:noting|mentioning|highlighting)|"
    r"in\s+(?:conclusion|summary|closing)[,\s]|"
    r"to\s+(?:sum\s+up|summarize|conclude)[,\s]|"
    r"(?:furthermore|moreover|additionally|consequently)[,\s]|"
    r"in\s+(?:the\s+realm\s+of|today\'s\s+(?:fast-paced|digital|ever-changing)\s+world)|"
    r"as\s+(?:we\s+(?:navigate|explore|delve\s+into)|an\s+ai)|"
    r"this\s+(?:comprehensive|multifaceted|nuanced)\s+(?:approach|analysis|guide)|"
    r"(?:rest\s+assured|without\s+(?:a\s+)?doubt|it\s+goes\s+without\s+saying)",
    re.IGNORECASE,
)

# Clickbait / sensationalist language
_CLICKBAIT = re.compile(
    r"\b(you\s+won\'t\s+believe|mind[\s-]?blowing|jaw[\s-]?dropping|"
    r"shocking(?:ly)?|unbelievable|incredible|this\s+is\s+why|this\s+is\s+how|"
    r"secret(?:ly)?|hidden\s+truth|they\s+don\'t\s+want\s+you|"
    r"what\s+(?:they\'re|the\s+media)\s+not\s+telling|wake\s+up|"
    r"bombshell|explosive\s+(?:reveal|report)|must[\s-]?see|"
    r"viral|trending|share\s+before\s+(?:it\'s\s+)?deleted)\b",
    re.IGNORECASE,
)

# Conspiracy / misinformation language
_CONSPIRACY = re.compile(
    r"\b(deep\s+state|new\s+world\s+order|mainstream\s+media\s+(?:lies?|hides?|ignores?)|"
    r"cover[\s-]?up|(?:false|staged)\s+flag|plandemic|scamdemic|"
    r"(?:they|elites?|globalists?)\s+(?:are\s+hiding|don\'t\s+want|control|plan(?:ning)?)|"
    r"sheep(?:le)?|(?:agenda|cabal|psyop)|"
    r"(?:bio)?weapon|(?:5G|vaccine|chemtrail)\s+(?:kill|harm|cause|spread)|"
    r"crisis\s+actor|hoax)\b",
    re.IGNORECASE,
)


# ─────────────────────────────────────────────────────────────────────────────
# Axis 1 – Text classification
# ─────────────────────────────────────────────────────────────────────────────

def classify_text(text: str) -> dict:
    """
    Classify text as real | ai_generated | altered.

    Strategy (layered):
    1. Explicit AI-generation markers → ai_generated immediately
    2. Heuristic scoring (AI prose patterns, clickbait, conspiracy)
    3. roberta-base-openai-detector model
    4. Combine model + heuristic scores
    """
    if not text or len(text.strip()) < 10:
        return {
            "category":   "real",
            "confidence": 0.5,
            "highlights": [],
            "reasoning":  "Text too short for reliable classification.",
            "is_news":    False,
        }

    is_news = bool(_NEWS_SIGNALS.search(text))

    # ── Layer 1: explicit AI disclosure ──────────────────────────────────────
    if _EXPLICIT_AI_SIGNALS.search(text):
        matches = _EXPLICIT_AI_SIGNALS.findall(text)[:3]
        return {
            "category":   "ai_generated",
            "confidence": 0.92,
            "highlights": matches,
            "reasoning":  f"Explicit AI-generation markers found: {matches}",
            "is_news":    is_news,
        }

    # ── Layer 2: heuristic scoring ────────────────────────────────────────────
    heuristic_score, heuristic_reasons = _heuristic_text_score(text)

    # ── Layer 3: model inference ──────────────────────────────────────────────
    model_category  = "real"
    model_confidence = 0.5
    model_reasoning  = "Model unavailable; using heuristics."

    try:
        from models import get_text_classifier
        with torch.inference_mode():
            results = get_text_classifier()(text[:512], truncation=True)

        scores = {r["label"]: r["score"] for r in results[0]}
        top_label = max(scores, key=scores.get)
        top_score = scores[top_label]
        model_category   = _map_label(top_label)
        model_confidence = round(top_score, 4)
        model_reasoning  = (
            f"Detector model: '{top_label}' ({top_score:.2%} confidence). "
            + (f"Heuristic signals: {heuristic_reasons[:2]}" if heuristic_reasons else "")
        )
    except Exception as exc:
        model_reasoning = f"Model error ({exc}); heuristics only."

    # ── Layer 4: blend scores ─────────────────────────────────────────────────
    # Model score: 0 = real, 1 = ai_generated
    model_ai_score = model_confidence if model_category == "ai_generated" else (1 - model_confidence)

    # Combined score (70% model, 30% heuristic)
    combined = 0.70 * model_ai_score + 0.30 * heuristic_score

    if combined > 0.50:
        final_category   = "ai_generated"
        final_confidence = round(combined, 4)
        reasoning = model_reasoning
        if heuristic_reasons:
            reasoning += f" AI prose patterns: {heuristic_reasons[:3]}"
    elif combined > 0.40:
        final_category   = "altered"
        final_confidence = round(combined, 4)
        reasoning = f"Moderate AI signals ({combined:.2%}). " + model_reasoning
    else:
        final_category   = "real"
        final_confidence = round(1 - combined, 4)
        reasoning = model_reasoning

    return {
        "category":   final_category,
        "confidence": final_confidence,
        "highlights": heuristic_reasons[:5],
        "reasoning":  reasoning,
        "is_news":    is_news,
    }


def _heuristic_text_score(text: str) -> tuple[float, list[str]]:
    """
    Returns (0..1 ai-probability, list-of-matched-signals).
    Higher = more likely AI-generated or misleading.
    """
    reasons: list[str] = []
    score = 0.0

    # AI prose vocabulary
    ai_matches = _AI_PROSE_PATTERNS.findall(text)
    if ai_matches:
        n  = min(len(ai_matches), 8)
        score += n * 0.07
        reasons.extend([m if isinstance(m, str) and m else "AI prose pattern" for m in ai_matches[:4]])

    # Clickbait
    cb = _CLICKBAIT.findall(text)
    if cb:
        score += min(len(cb), 4) * 0.08
        reasons.append(f"clickbait language: {cb[:2]}")

    # Conspiracy
    cn = _CONSPIRACY.findall(text)
    if cn:
        score += min(len(cn), 4) * 0.10
        reasons.append(f"misinformation language: {cn[:2]}")

    # Very uniform sentence length (AI tends to write evenly-sized sentences)
    sentences = re.split(r"[.!?]+", text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 10]
    if len(sentences) >= 4:
        lengths = [len(s.split()) for s in sentences]
        mean    = sum(lengths) / len(lengths)
        variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
        if variance < 10 and mean > 12:  # very uniform, moderately long
            score += 0.12
            reasons.append("uniform sentence length (AI indicator)")

    return min(score, 1.0), reasons


def _map_label(label: str) -> str:
    """Map model output labels → our taxonomy."""
    label_lower = label.lower()
    # openai-community/roberta-base-openai-detector
    if label_lower == "fake":
        return "ai_generated"
    if label_lower == "real":
        return "real"
    # Hello-SimpleAI/chatgpt-detector-roberta
    if "chatgpt" in label_lower or "ai" in label_lower:
        return "ai_generated"
    if "human" in label_lower:
        return "real"
    # Generic fallback
    if any(k in label_lower for k in ("fake", "generated", "machine", "gpt", "synthetic")):
        return "ai_generated"
    if any(k in label_lower for k in ("alter", "manip", "edit")):
        return "altered"
    return "real"


# ─────────────────────────────────────────────────────────────────────────────
# Axis 1 – Image classification
# ─────────────────────────────────────────────────────────────────────────────

def classify_image(image_b64: str) -> dict:
    """
    Detect AI-generated / manipulated images via frequency-domain heuristics.
    AI-generated images have smoother spectral distributions (less high-freq noise).
    """
    try:
        raw   = base64.b64decode(image_b64)
        score = _heuristic_image_score(raw)

        if score > 0.65:
            category  = "ai_generated"
            reasoning = "High frequency-domain smoothness suggests AI synthesis (GAN/diffusion)."
        elif score > 0.40:
            category  = "altered"
            reasoning = "Moderate spectral inconsistency suggests post-processing or manipulation."
        else:
            category  = "real"
            reasoning = "Frequency distribution consistent with an unedited photograph."

        return {
            "category":   category,
            "confidence": round(score, 4),
            "highlights": [],
            "reasoning":  reasoning,
            "is_news":    False,
        }
    except Exception as exc:
        return {
            "category":   "real",
            "confidence": 0.3,
            "highlights": [],
            "reasoning":  f"Image analysis failed: {exc}",
            "is_news":    False,
        }


def _heuristic_image_score(raw_bytes: bytes) -> float:
    """
    FFT-based AI-image detector proxy.
    AI images (GAN/diffusion) have a higher ratio of energy in low frequencies.
    """
    try:
        import numpy as np
        from PIL import Image

        img = Image.open(io.BytesIO(raw_bytes)).convert("L").resize((64, 64))
        arr = np.array(img, dtype=np.float32)
        fft_shift = np.fft.fftshift(np.fft.fft2(arr))
        magnitude = np.abs(fft_shift)

        h, w = magnitude.shape
        cy, cx = h // 2, w // 2
        r = min(h, w) // 4

        y_idx, x_idx = np.ogrid[:h, :w]
        low_mask = (y_idx - cy) ** 2 + (x_idx - cx) ** 2 <= r ** 2
        low_energy  = magnitude[low_mask].sum()
        total_energy = magnitude.sum() + 1e-9

        low_ratio = low_energy / total_energy
        return float(min(low_ratio * 1.5, 1.0))
    except Exception:
        return 0.3


# ─────────────────────────────────────────────────────────────────────────────
# Axis 2 – Context confidence
# ─────────────────────────────────────────────────────────────────────────────

def check_context(text: str, image_b64: Optional[str]) -> dict:
    """
    Detect semantic mismatch between caption and image, OR misleading text alone.
    """
    if not text:
        return {
            "is_misleading": False,
            "confidence":    0.0,
            "explanation":   "No text provided.",
        }

    if image_b64:
        return _clip_check(text, image_b64)

    return _text_context_check(text)


def _clip_check(caption: str, image_b64: str) -> dict:
    try:
        from PIL import Image
        from models import get_clip

        raw   = base64.b64decode(image_b64)
        image = Image.open(io.BytesIO(raw)).convert("RGB")
        model, processor = get_clip()

        inputs = processor(
            text=[caption[:77]], images=image,
            return_tensors="pt", padding=True, truncation=True,
        )
        with torch.inference_mode():
            outputs    = model(**inputs)
            similarity = outputs.logits_per_image.softmax(dim=1)[0][0].item()

        is_misleading = similarity < 0.25
        confidence    = round(1.0 - similarity, 4)
        explanation   = (
            f"Image–caption CLIP similarity: {similarity:.2f}. "
            + ("Low similarity — image may not match the text description." if is_misleading
               else "Image and caption appear semantically consistent.")
        )
        return {"is_misleading": is_misleading, "confidence": confidence, "explanation": explanation}
    except Exception as exc:
        # Fall through to text-only check if CLIP fails
        return _text_context_check(caption)


def _text_context_check(text: str) -> dict:
    """
    Layered heuristics: recycled media, clickbait, conspiracy language.
    Returns first match found (most specific → most general).
    """
    # 1. Old/recycled media
    reuse = re.findall(
        r"\b(old\s+(?:photo|video|image|footage|clip)|from\s+\d{4}|"
        r"originally\s+(?:from|posted|shared)|taken\s+in\s+\d{4}|"
        r"archive\s+(?:photo|footage)|file\s+photo|stock\s+(?:image|photo)|"
        r"not\s+related\s+to|unrelated\s+to|misidentified)\b",
        text, re.IGNORECASE,
    )
    if reuse:
        return {
            "is_misleading": True,
            "confidence":    0.80,
            "explanation":   f"Recycled/misattributed media signals: {list(set(reuse))[:3]}",
        }

    # 2. Conspiracy / misinformation vocabulary
    conspiracy = _CONSPIRACY.findall(text)
    if conspiracy:
        return {
            "is_misleading": True,
            "confidence":    0.72,
            "explanation":   f"Misinformation language patterns: {list(set(conspiracy))[:3]}",
        }

    # 3. Heavy clickbait
    cb = _CLICKBAIT.findall(text)
    if len(cb) >= 2:
        return {
            "is_misleading": True,
            "confidence":    0.60,
            "explanation":   f"Sensationalist / clickbait language: {list(set(cb))[:3]}",
        }

    # 4. AI prose (misleading in a different way — synthetic content masquerading as human)
    ai_matches = _AI_PROSE_PATTERNS.findall(text)
    if len(ai_matches) >= 3:
        labels = [m for m in ai_matches if isinstance(m, str) and m.strip()][:3]
        return {
            "is_misleading": True,
            "confidence":    0.55,
            "explanation":   f"AI-generated prose patterns detected — content may be synthetic: {labels}",
        }

    return {
        "is_misleading": False,
        "confidence":    0.08,
        "explanation":   "No misleading context signals detected.",
    }
