"use client";

import { FormEvent, useState } from "react";

type TruthRetrievalResponse = {
  is_news?: boolean;
  is_misinformation?: boolean;
  confidence?: number;
  verdict?: string;
  explanation?: string;
  corrected_version?: string;
  sources?: unknown[];
  service?: unknown;
  error?: string;
};

const PAGE_COPY = {
  headerTitle: "Verify a claim",
  headerSubtitle:
    "Check whether a claim is accurate using external sources and confidence signals.",
  requestTitle: "1) Enter the claim",
  requestSubtitle:
    "Paste the statement you want to verify. Optional metadata can improve retrieval quality.",
  resultTitle: "2) Verification result",
  resultSubtitle:
    "Review the verdict, confidence, and explanation generated by the truth retrieval service.",
  advancedTitle: "Advanced technical output",
  advancedSubtitle:
    "Detailed service payload for troubleshooting and engineering use.",
};

export default function TruthRetrievalPage() {
  const [sessionId] = useState(`manual-${Date.now()}`);
  const [cleanText, setCleanText] = useState("");
  const [metadataJson, setMetadataJson] = useState("{}");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState<TruthRetrievalResponse | null>(null);

  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setLoading(true);
    setError("");
    setResult(null);

    try {
      const metadata = JSON.parse(metadataJson) as Record<string, unknown>;
      const response = await fetch("/api/truth-retrieval", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          session_id: sessionId,
          clean_text: cleanText,
          content_type: "text",
          metadata,
        }),
      });

      const body = (await response.json()) as TruthRetrievalResponse;
      if (!response.ok) {
        throw new Error(body.error || `Request failed (${response.status})`);
      }
      setResult(body);
    } catch (submitError) {
      setError(
        submitError instanceof Error
          ? submitError.message
          : "Unexpected error while calling truth retrieval service",
      );
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="app-page">
      <header className="app-header panel p-5 md:p-6">
        <span className="endpoint-kicker">Truth retrieval</span>
        <h1 className="app-title">{PAGE_COPY.headerTitle}</h1>
        <p className="app-subtitle">{PAGE_COPY.headerSubtitle}</p>
      </header>

      <section className="panel p-5 md:p-6">
        <div className="mb-4 space-y-1">
          <h2 className="section-title">{PAGE_COPY.requestTitle}</h2>
          <p className="section-description">{PAGE_COPY.requestSubtitle}</p>
        </div>

        <form className="space-y-5" onSubmit={onSubmit}>
          <p className="muted-note">
            Session ID is auto-generated for tracking: <span className="font-mono">{sessionId}</span>
          </p>

          <label className="form-label">
            Claim text
            <textarea
              className="input-control min-h-32"
              value={cleanText}
              onChange={(event) => setCleanText(event.target.value)}
              placeholder="Paste the claim text to verify"
              required
            />
          </label>

          <label className="form-label">
            Optional metadata (JSON)
            <textarea
              className="input-control min-h-24 font-mono text-xs"
              value={metadataJson}
              onChange={(event) => setMetadataJson(event.target.value)}
            />
          </label>

          <button
            className="primary-btn"
            disabled={loading}
            type="submit"
          >
            {loading ? "Running..." : "Verify claim"}
          </button>
        </form>
      </section>

      {error ? (
        <section className="alert-error">
          {error}
        </section>
      ) : null}

      {result ? (
        <section className="grid gap-4 md:grid-cols-2">
          <article className="panel p-5">
            <h2 className="section-title">{PAGE_COPY.resultTitle}</h2>
            <p className="section-description mb-3">{PAGE_COPY.resultSubtitle}</p>
            <div className="mb-3 flex flex-wrap gap-2">
              <span className="stat-chip">
                Verdict: {result.verdict ?? "n/a"}
              </span>
              <span className="stat-chip">
                Confidence: {result.confidence ?? "n/a"}
              </span>
            </div>
            <div className="space-y-2 text-sm">
              <p><strong>Is News:</strong> {String(result.is_news ?? false)}</p>
              <p><strong>Is Misinformation:</strong> {String(result.is_misinformation ?? false)}</p>
              <p><strong>Explanation:</strong> {result.explanation ?? ""}</p>
            </div>
            <pre className="code-block">
              {JSON.stringify(
                {
                  corrected_version: result.corrected_version,
                  sources: result.sources,
                },
                null,
                2,
              )}
            </pre>
          </article>

          <article className="panel p-5">
            <h2 className="section-title">{PAGE_COPY.advancedTitle}</h2>
            <p className="section-description mb-3">{PAGE_COPY.advancedSubtitle}</p>
            <details>
              <summary className="cursor-pointer text-sm font-medium text-violet-700 dark:text-violet-300">
                Show advanced JSON
              </summary>
              <pre className="code-block max-h-[32rem]">
                {JSON.stringify({ service: result.service }, null, 2)}
              </pre>
            </details>
          </article>
        </section>
      ) : null}
    </main>
  );
}
